name: 'Build setup'
description: 'Checks out the code and setups gradle'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Show java version
      shell: bash
      run: java -version
    - name: Validate checksum gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: "Setup Gradle"
      uses: gradle/gradle-build-action@v2
      with:
        # Cache results from main and release branches only per docs
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
    - name: Build mobile core
      uses: ./.github/actions/build-core
