default_platform(:android)

platform :android do
    desc "Runs all the tests"
    lane :test do
        gradle(task: "test")
    end

    desc "Executes Android lint"
    lane :lint do
        gradle(task: "lintCoronatesterProductionRelease")
    end

    desc "Builds and distributes app via firebase"
    lane :distribute do

        deploy_test

        deploy_acc

        deploy_prod

    end

    private_lane :deploy_test do
        build_android_app(
                    task: "assemble",
                    flavor: "coronatesterTest",
                    build_type: "Debug"
         )

        firebase_app_distribution(
            app: "1:168257592968:android:156fcae99be6d74526493d",
            firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
            groups: "testers",
            release_notes: "Release on test environment via Firebase"
        )
    end


    private_lane :deploy_acc do
            build_android_app(
                        task: "assemble",
                        flavor: "coronatesterAcceptance",
                        build_type: "Release"
             )

            firebase_app_distribution(
                app: "1:406021306322:android:27abb9a50f0543152cfa0b",
                firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
                groups: "testers",
                release_notes: "Release on acceptance environment via Firebase"
            )
     end



    private_lane :deploy_prod do
             build_android_app(
                         task: "assemble",
                         flavor: "coronatesterProduction",
                         build_type: "Release"
              )

             firebase_app_distribution(
                 app: "1:625955224267:android:742af66e140333db97794e",
                 firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
                 groups: "testers",
                 release_notes: "Release on production environment via Firebase"
             )
    end

end
