name: 'Build mobile core'
description: 'Builds the mobile core library'
runs:
  using: "composite"
  steps:
    - name: Get mobile core version
      id: version
      run: |
        echo "::set-output name=VERSION::`git rev-parse HEAD`"
      working-directory: mobilecore-src
      shell: bash
    - name: Restore from cache
      id: corecache
      uses: actions/cache@v2
      with:
        path: |
          mobilecore/mobilecore.aar
        key: mobilecore-aar-${{ steps.version.outputs.VERSION }}-${{ hashfiles('mobilecore/build.gradle') }}
    - name: Setup go
      if: steps.corecache.outputs.cache-hit != 'true'
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
      with:
        go-version-file: 'mobilecore-src/go.mod'
    - name: Build mobile core
      if: steps.corecache.outputs.cache-hit != 'true'
      run: |
        if [ `uname` == "Darwin" ]; then
          export ARCH="mac"
        else
          export ARCH="linux"
        fi
        # Install NDK because it's too old on the Github runner image used
        wget -q https://dl.google.com/android/repository/commandlinetools-$ARCH-8512546_latest.zip
        unzip commandlinetools-$ARCH-8512546_latest.zip
        export SDK_ROOT=$PWD/cmdline-tools
        bash -c "yes || true" | cmdline-tools/bin/sdkmanager --licenses --sdk_root=$SDK_ROOT
        cmdline-tools/bin/sdkmanager 'ndk;21.4.7075529' --sdk_root=$SDK_ROOT
        export ANDROID_NDK_HOME=$SDK_ROOT/ndk/21.4.7075529
        ./gradlew mobilecore:buildCore
      shell: bash
