name: End to end tests

on:
  schedule:
    - cron: '0 5 * * 2,4' # Run at 05:00 on Tuesday and Thursday.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: ./.github/actions/setup
      - name: Spotless
        run: ./gradlew spotlessCheck
      - name: Test
        run: ./gradlew connectedAccDebugAndroidTest
      - name: Run tests on Testlab
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        if: contains(env.FIREBASE_SERVICE_ACCOUNT, '{') && !contains(github.event.pull_request.labels.*.name, 'skip-screenshot-tests')
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT > $RUNNER_TEMP/.firebase_service_account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/.firebase_service_account.json >> $GITHUB_ENV
          ./gradlew holder:runFlank
      - name: Archive end to end test-results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: end2end-test-results
          path: |
            holder/build/reports
          retention-days: 2
