name: End to end tests

on:
  schedule:
    - cron: '0 13 * * 0' # Run at 13:00 on Sunday.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set version number
        run: |
          version=$(( $GITHUB_RUN_NUMBER + 4000 ))
          echo VERSION_NUMBER=$version >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - id: setup
        uses: ./.github/actions/setup
      - name: Assemble
        run: ./gradlew holder:assemAccDebug holder:assemAccDebugAndroidTest
      - name: Run tests on Firebase Test Lab
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo $FIREBASE_SERVICE_ACCOUNT > $RUNNER_TEMP/.firebase_service_account.json
          export GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/.firebase_service_account.json >> $GITHUB_ENV
          ./gradlew holder:runFlankEnd2end -Pandroid.testInstrumentationRunnerArguments.authPassword=${{ secrets.ACCEPTANCE_BASIC_AUTH_PASSWORD }}
      - name: Slack Notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_URL }}
          SLACK_MESSAGE: 'New test run for Android :android:'
        uses: rtCamp/action-slack-notify@v2
