name: UI Tests on demand

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set version number
        run: |
          version=$(( $GITHUB_RUN_NUMBER + 4000 ))
          echo VERSION_NUMBER=$version >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - id: setup
        uses: ./.github/actions/setup
      - name: Assemble
        run: ./gradlew holder:assemAccDebug holder:assemAccDebugAndroidTest
